services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8088:8080"
      - "30500:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - jenkins
    restart: unless-stopped


volumes:
  jenkins_home:

networks:
  jenkins: